-- KASB DIGITAL - Database setup
-- Run this file in Supabase SQL Editor.

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 40),
  rating integer not null check (rating between 1 and 5),
  comment text not null check (char_length(comment) between 1 and 500),
  created_at timestamptz not null default now(),
  approved boolean not null default true
);

create table if not exists public.verification_codes (
  id bigint generated by default as identity primary key,
  code text not null unique check (char_length(code) between 4 and 40),
  order_label text,
  used boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;
alter table public.verification_codes enable row level security;
alter table public.admin_users enable row level security;

-- Admin helper. Add the Supabase Auth user's UUID to admin_users after creating the admin account.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admin_users where user_id = auth.uid());
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "public can read approved reviews" on public.reviews;
create policy "public can read approved reviews"
on public.reviews for select to anon, authenticated
using (approved = true or public.is_admin());

drop policy if exists "public can submit reviews" on public.reviews;
-- Direct inserts are intentionally disabled. Reviews are created only through the verified RPC below.


drop policy if exists "admins can update reviews" on public.reviews;
create policy "admins can update reviews"
on public.reviews for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins can delete reviews" on public.reviews;
create policy "admins can delete reviews"
on public.reviews for delete to authenticated
using (public.is_admin());

drop policy if exists "admins can read codes" on public.verification_codes;
create policy "admins can read codes"
on public.verification_codes for select to authenticated
using (public.is_admin());

drop policy if exists "admins can insert codes" on public.verification_codes;
create policy "admins can insert codes"
on public.verification_codes for insert to authenticated
with check (public.is_admin());

drop policy if exists "admins can delete codes" on public.verification_codes;
create policy "admins can delete codes"
on public.verification_codes for delete to authenticated
using (public.is_admin());

-- Anonymous/customer-safe function: validates a one-time purchase code, inserts the review,
-- and marks the code used in one transaction.
create or replace function public.submit_verified_review(
  p_code text,
  p_name text,
  p_rating integer,
  p_comment text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if char_length(trim(coalesce(p_name,''))) not between 1 and 40 then raise exception 'INVALID_DATA'; end if;
  if p_rating not between 1 and 5 then raise exception 'INVALID_DATA'; end if;
  if char_length(trim(coalesce(p_comment,''))) not between 1 and 500 then raise exception 'INVALID_DATA'; end if;

  update public.verification_codes
  set used = true
  where upper(code) = upper(trim(p_code)) and used = false;

  if not found then raise exception 'INVALID_CODE'; end if;

  insert into public.reviews(name, rating, comment, approved)
  values (trim(p_name), p_rating, trim(p_comment), true)
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.submit_verified_review(text,text,integer,text) from public;
grant execute on function public.submit_verified_review(text,text,integer,text) to anon, authenticated;

-- Protect tables from direct client writes; the RPC is the only customer review path.
revoke insert, update, delete on public.reviews from anon, authenticated;
revoke select, insert, update, delete on public.verification_codes from anon;

-- Realtime (safe to run even if it was already added).
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'reviews'
  ) then
    alter publication supabase_realtime add table public.reviews;
  end if;
end $$;

-- IMPORTANT: after creating the admin user in Supabase Auth, run this with that user's UUID:
-- insert into public.admin_users(user_id) values ('YOUR-AUTH-USER-UUID');
