-- نفّذ هذا الملف كاملًا داخل Supabase > SQL Editor

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 40),
  rating integer not null check (rating between 1 and 5),
  comment text not null check (char_length(comment) between 1 and 500),
  created_at timestamptz not null default now(),
  approved boolean not null default true
);

alter table public.reviews enable row level security;

drop policy if exists "public can read approved reviews" on public.reviews;
create policy "public can read approved reviews"
on public.reviews for select
to anon, authenticated
using (approved = true);

drop policy if exists "public can submit reviews" on public.reviews;
create policy "public can submit reviews"
on public.reviews for insert
to anon, authenticated
with check (
  approved = true
  and char_length(name) between 1 and 40
  and char_length(comment) between 1 and 500
  and rating between 1 and 5
);

-- تفعيل Realtime للتحديث الفوري إذا كان متاحًا في مشروعك:
alter publication supabase_realtime add table public.reviews;